---
version: "3.1"

services:
  web:
    image: vishalgpt579-dev
    build:
      context: ./
    ports:
      - 4000:4000
    command: jekyll serve --host 0.0.0.0
    working_dir: /app
    volumes:
      - $PWD:/app

